import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Shivanshu | Web Developer & Software Engineer Portfolio",
  description: "Portfolio of a full stack developer, web developer, software engineer, and digital marketing expert building modern and interactive web applications.",
  keywords: [
    "web developer",
    "full stack developer",
    "software engineer",
    "digital marketing",
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Sanidhya Kumar Verma",
    url: "#",
  },
  openGraph: {
    title: "Shivanshu | Web Developer & Software Engineer Portfolio",
    description: "Portfolio of a full stack developer, web developer, software engineer, and digital marketing expert.",
    type: "website",
    url: "#",
    siteName: "Space Portfolio",
  },
  icons: {
    icon: "/logo.png",
  },
} as const;
